// textTypes.js — source of truth for all text type data
// Layout line kinds:
//   { k:'3col', l, c, r }       three-column row (left / center / right)
//   { k:'right', t }            right-aligned
//   { k:'left',  t }            left-aligned
//   { k:'center', t }           centered
//   { k:'indent', t }           body paragraph, indented 2em (Chinese standard)
//   { k:'blank' }               empty line spacer
//   { k:'divider' }             thin hr
//   { k:'field', label, t }     header field  label: value
//   { k:'bullet', t }           bullet-list item
//   { k:'qa', role, t, isQ }    interview Q&A line
//   { k:'stats', likes, comments, shares, views }  blog engagement row
// Each line may carry { note } shown in the format-rules overlay

const TEXT_TYPES = [
  // ─── 1. 日记 ─────────────────────────────────────────────────────────────────
  // MD spec: Header (date SP day SP weather, LA); Body (I2); No sign-off
  {
    id: 'diary', char: '记', zhName: '日记', pinyin: 'rìjì', enName: 'Diary Entry', color: '#4A3728',
    tagline: 'Personal daily journal — private, reflective, first-person',
    formatRules: [
      'First line: date (left-aligned) | day of week (centered) | weather (right-aligned)',
      'First line of each body paragraph indented 2 Chinese characters (2em)',
      'One blank line between paragraphs',
      'Use first person (我) throughout',
      'No greeting or signature required',
      'End with a reflection or plan for tomorrow',
    ],
    layout: [
      { k: '3col', l: '2026年4月19日', c: '星期日', r: '天气：晴', note: 'Date · Day · Weather — one line, three columns' },
      { k: 'blank' },
      { k: 'indent', t: '今天是一个非常特别的日子！我和家人去了一个中国文化节，我们看了舞龙表演，真的很精彩！', note: 'Body paragraph — indented 2 chars' },
      { k: 'blank' },
      { k: 'indent', t: '上午我们先去了一个书法展览，我尝试写了自己的名字，虽然写得不太好，但是老师说我进步很快。下午我们吃了很多中国食物，比如包子和春卷，味道太好了！' },
      { k: 'blank' },
      { k: 'indent', t: '我觉得今天非常开心，因为我学到了很多关于中国文化的知识。我希望下次还能参加这样的活动。' },
      { k: 'blank' },
      { k: 'indent', t: '明天我打算把今天学到的汉字练习一下。', note: 'Reflection / plan for tomorrow' },
    ],
    phrases: [
      { zh: '今天是……', pinyin: 'Jīntiān shì…', en: 'Today is…' },
      { zh: '我觉得……，因为……', pinyin: 'Wǒ juéde…, yīnwèi…', en: 'I feel… because…' },
      { zh: '首先……然后……最后……', pinyin: 'Shǒuxiān… ránhòu… zuìhòu…', en: 'First… then… finally…' },
      { zh: '真的很……', pinyin: 'Zhēn de hěn…', en: 'It was really…' },
      { zh: '我希望……', pinyin: 'Wǒ xīwàng…', en: 'I hope…' },
      { zh: '明天我打算……', pinyin: 'Míngtiān wǒ dǎsuàn…', en: 'Tomorrow I plan to…' },
      { zh: '这让我……', pinyin: 'Zhè ràng wǒ…', en: 'This made me…' },
      { zh: '虽然……但是……', pinyin: 'Suīrán… dànshì…', en: 'Although… but…' },
    ],
    checklist: [
      { zh: '日期行', en: 'Header: date (left) | day (center) | weather (right)' },
      { zh: '天气', en: 'Weather noted on the first line' },
      { zh: '第一人称', en: 'Consistent use of 我 throughout' },
      { zh: '缩进', en: "Each paragraph's first line indented 2 Chinese chars" },
      { zh: '段落空行', en: 'Blank line between every paragraph' },
      { zh: '感受', en: 'Personal feelings expressed (我觉得 / 我感到)' },
      { zh: '时间词', en: 'Time markers used (早上 / 下午 / 晚上)' },
      { zh: '结尾', en: 'Reflection or plan for tomorrow at the end' },
    ],
  },

  // ─── 2. 信 ───────────────────────────────────────────────────────────────────
  // MD spec: Greeting (LA + C); Body (I2); Wish: "祝" on NL (LA) → Blessing (I2);
  //          Name (RA) → Date on next NL (RA)
  {
    id: 'letter', char: '信', zhName: '信', pinyin: 'xìn', enName: 'Letter', color: '#C0392B',
    tagline: 'Formal or informal written letter',
    formatRules: [
      'Greeting left-aligned at margin with colon: 亲爱的XX:',
      'First line of each body paragraph indented 2 Chinese characters (2em)',
      'One blank line between paragraphs',
      '"祝" on a new line, left-aligned; the blessing on the next line, indented 2 chars',
      'Name right-aligned',
      'Date right-aligned on the line below the name: YYYY年MM月DD日',
    ],
    layout: [
      { k: 'left', t: '亲爱的小红：', note: 'Greeting — left-aligned, ends with colon (：)' },
      { k: 'blank' },
      { k: 'indent', t: '你好！好久不见，最近怎么样？我非常想念你！', note: 'Body paragraph — indented 2 chars' },
      { k: 'blank' },
      { k: 'indent', t: '上个月我们学校举办了一个文化节，我学会了包饺子。你知道吗，饺子非常好吃！我想以后教你怎么做。' },
      { k: 'blank' },
      { k: 'indent', t: '你今年暑假有什么计划？我希望我们能在假期见面。' },
      { k: 'blank' },
      { k: 'indent', t: '期待你的回信！' },
      { k: 'blank' },
      { k: 'left',  t: '祝', note: '"祝" — left-aligned on its own line' },
      { k: 'indent', t: '好！', note: 'Blessing — indented on the next line' },
      { k: 'blank' },
      { k: 'right', t: '小明', note: 'Name — right-aligned' },
      { k: 'right', t: '2026年04月19日', note: 'Date — right-aligned, below name (YYYY年MM月DD日)' },
    ],
    phrases: [
      { zh: '好久不见', pinyin: 'Hǎojiǔ bù jiàn', en: 'Long time no see' },
      { zh: '我非常想念你', pinyin: 'Wǒ fēicháng xiǎngniàn nǐ', en: 'I miss you very much' },
      { zh: '我想跟你说……', pinyin: 'Wǒ xiǎng gēn nǐ shuō…', en: 'I want to tell you…' },
      { zh: '希望收到你的回信', pinyin: 'Xīwàng shōudào nǐ de huí xìn', en: 'Hope to hear back from you soon' },
      { zh: '此致敬礼', pinyin: 'Cǐ zhì jìng lǐ', en: 'Yours respectfully (formal)' },
      { zh: '你永远的朋友', pinyin: "Nǐ yǒngyuǎn de péngyǒu", en: 'Your forever friend' },
      { zh: '最近怎么样？', pinyin: 'Zuìjìn zěnmeyàng?', en: 'How have you been lately?' },
      { zh: '我写信是想……', pinyin: 'Wǒ xiě xìn shì xiǎng…', en: 'I am writing because I want to…' },
    ],
    checklist: [
      { zh: '称呼', en: 'Greeting left-aligned, ends with colon (亲爱的... ：)' },
      { zh: '目的', en: 'Reason for writing stated early' },
      { zh: '正文缩进', en: "Each paragraph's first line indented 2 characters" },
      { zh: '段落空行', en: 'Blank line between paragraphs' },
      { zh: '祝+祝福', en: '"祝" left-aligned; blessing indented on next line' },
      { zh: '署名', en: 'Name right-aligned' },
      { zh: '日期（信尾）', en: 'Date bottom right: YYYY年MM月DD日' },
    ],
  },

  // ─── 3. 电子邮件 ──────────────────────────────────────────────────────────────
  // MD spec: 4 header fields LA (寄件人/收件人/主题/日期); Greeting (LA + C);
  //          Body (I2); Sign-off Name (LA at bottom)
  {
    id: 'email', char: '邮', zhName: '电子邮件', pinyin: 'diànzǐ yóujiàn', enName: 'Email', color: '#2E7D6B',
    tagline: 'Electronic written communication',
    formatRules: [
      'Four header fields left-aligned: 寄件人 (From), 收件人 (To), 主题 (Subject), 日期 (Date)',
      'Divider line separates header from body',
      'Greeting left-aligned at margin with colon: 尊敬的XX：',
      'All body lines left-aligned at the margin — no indentation (unlike letters)',
      'One blank line between paragraphs',
      'Closing phrase left-aligned (unlike letters — do not right-align)',
      'Name left-aligned below closing phrase',
    ],
    layout: [
      { k: 'field', label: '发件人：', t: 'wang.ming@school.edu', note: 'From — left-aligned header fields' },
      { k: 'field', label: '收件人：', t: 'li.laoshi@school.edu' },
      { k: 'field', label: '主　题：', t: '关于下周的汉语文化节活动', note: 'Subject line' },
      { k: 'field', label: '日　期：', t: '2026年4月19日' },
      { k: 'divider', note: 'Divider separates header from body' },
      { k: 'left', t: '尊敬的李老师：', note: 'Greeting — left-aligned, ends with colon (：)' },
      { k: 'blank' },
      { k: 'left', t: '您好！我写信是想询问一下下周的汉语文化节活动。我非常感兴趣，想了解更多信息。', note: 'Body — left-aligned, no indentation' },
      { k: 'blank' },
      { k: 'left', t: '请问活动什么时候开始？需要提前报名吗？我可以带朋友一起来吗？' },
      { k: 'blank' },
      { k: 'left', t: '期待您的回复，谢谢！' },
      { k: 'blank' },
      { k: 'left', t: '祝好，', note: 'Closing — left-aligned (unlike letters)' },
      { k: 'left', t: '王明', note: 'Name — left-aligned' },
    ],
    phrases: [
      { zh: '我写信是为了……', pinyin: 'Wǒ xiě xìn shì wèile…', en: 'I am writing to…' },
      { zh: '请问……', pinyin: 'Qǐngwèn…', en: 'May I ask…' },
      { zh: '非常感谢您的帮助', pinyin: 'Fēicháng gǎnxiè nín de bāngzhù', en: 'Thank you very much for your help' },
      { zh: '期待您的回复', pinyin: 'Qīdài nín de huífù', en: 'Looking forward to your reply' },
      { zh: '如有任何问题，请联系我', pinyin: 'Rú yǒu rènhé wèntí, qǐng liánxì wǒ', en: 'If you have any questions, contact me' },
      { zh: '此致敬礼', pinyin: 'Cǐ zhì jìng lǐ', en: 'Yours sincerely (formal close)' },
      { zh: '祝你快乐', pinyin: 'Zhù nǐ kuàilè', en: 'Wishing you happiness (informal)' },
      { zh: '我想了解更多关于……的信息', pinyin: 'Wǒ xiǎng liǎojiě gèng duō guānyú… de xìnxī', en: 'I would like more information about…' },
    ],
    checklist: [
      { zh: '发件人', en: 'From field included (寄件人：)' },
      { zh: '收件人', en: 'To field included (收件人：)' },
      { zh: '主题', en: 'Subject line written (主题：)' },
      { zh: '日期', en: 'Date field included (日期：)' },
      { zh: '称呼', en: 'Greeting left-aligned, ends with colon (尊敬的... / 亲爱的...)' },
      { zh: '目的', en: 'Purpose stated clearly in opening' },
      { zh: '正文缩进', en: 'Body paragraphs indented 2 characters' },
      { zh: '段落空行', en: 'One blank line between paragraphs' },
      { zh: '结束语', en: 'Closing phrase left-aligned (祝好 / 期待回复)' },
      { zh: '署名', en: 'Name signed at end — left-aligned' },
    ],
  },

  // ─── 4. 便条 ─────────────────────────────────────────────────────────────────
  // MD spec: Recipient (LA + C); Body (I2);
  //          Sender/Identity (RA) → Date on next NL (RA)
  {
    id: 'note', char: '条', zhName: '便条', pinyin: 'biàntiáo', enName: 'Note / Message', color: '#7B6EA8',
    tagline: 'Short informal written message',
    formatRules: [
      'Recipient left-aligned at margin with colon: XX：',
      'Body paragraphs indented 2 Chinese characters (2em)',
      'One blank line between paragraphs',
      'Sender name right-aligned',
      'Date right-aligned on the line below the name',
    ],
    layout: [
      { k: 'left',   t: '小红：', note: 'Recipient — left-aligned, ends with colon (：)' },
      { k: 'blank' },
      { k: 'indent', t: '我今天下午有补习，不能和你一起去图书馆了。对不起！', note: 'Body — indented 2 chars' },
      { k: 'blank' },
      { k: 'indent', t: '我们可以明天下午两点在咖啡厅见面吗？请回复我。' },
      { k: 'blank' },
      { k: 'right',  t: '小明', note: 'Name — right-aligned' },
      { k: 'right',  t: '2026年4月19日', note: 'Date — right-aligned, below name' },
    ],
    phrases: [
      { zh: '我想告诉你……', pinyin: 'Wǒ xiǎng gàosù nǐ…', en: 'I want to tell you…' },
      { zh: '对不起，我不能……', pinyin: 'Duìbuqǐ, wǒ bù néng…', en: "Sorry, I can't…" },
      { zh: '我们可以……吗？', pinyin: 'Wǒmen kěyǐ… ma?', en: 'Can we…?' },
      { zh: '请回复我', pinyin: 'Qǐng huífù wǒ', en: 'Please reply to me' },
      { zh: '别忘了……', pinyin: 'Bié wàngle…', en: "Don't forget…" },
      { zh: '记得……', pinyin: 'Jìde…', en: 'Remember to…' },
      { zh: '我今天不能……', pinyin: 'Wǒ jīntiān bù néng…', en: "I can't… today" },
      { zh: '改天再说', pinyin: 'Gǎitiān zài shuō', en: "Let's talk another day" },
    ],
    checklist: [
      { zh: '称呼', en: 'Recipient named at start (XX：) — left-aligned' },
      { zh: '内容简短', en: 'Message is brief (3–5 sentences max)' },
      { zh: '正文缩进', en: 'Body indented 2 characters' },
      { zh: '目的明确', en: 'Main point stated immediately' },
      { zh: '署名', en: 'Your name right-aligned at the end' },
      { zh: '日期', en: 'Date right-aligned below name' },
    ],
  },

  // ─── 5. 通知 ─────────────────────────────────────────────────────────────────
  // MD spec: Title (CA); Body (I2 paragraphs OR LA categorised fields);
  //          Issuing Org (RA) → Date (RA)
  {
    id: 'notice', char: '告', zhName: '通知', pinyin: 'tōngzhī', enName: 'Notice', color: '#5B6EA8',
    tagline: 'Formal announcement for a specific audience',
    formatRules: [
      'Issuing organisation right-aligned at top (e.g. 中文办公室)',
      'Date right-aligned below the org name, above the title: YYYY年MM月DD日',
      '"通知" title centered (larger font)',
      'Audience left-aligned at margin: 全体同学：',
      'First line of each body paragraph indented 2 Chinese characters (2em)',
      'One blank line between paragraphs',
      'Issuing body right-aligned at bottom',
    ],
    layout: [
      { k: 'right',  t: '中文办公室', note: 'Issuing org — right-aligned at top' },
      { k: 'right',  t: '2026年4月19日', note: 'Date — right-aligned below org, above title' },
      { k: 'blank' },
      { k: 'center', t: '通　知', note: 'Title — centered' },
      { k: 'blank' },
      { k: 'left',   t: '全体同学：', note: 'Audience — left-aligned, ends with colon' },
      { k: 'blank' },
      { k: 'indent', t: '学校将于下周五（4月25日）举办汉语文化节。活动将在学校礼堂举行，时间为上午九点至下午三点。', note: 'Body — indented 2 chars' },
      { k: 'blank' },
      { k: 'indent', t: '本次活动包括书法展览、中国传统音乐表演以及美食品尝等环节。请各位同学积极参与，并于本周三前向班主任报名。' },
      { k: 'blank' },
      { k: 'indent', t: '参加活动的同学请穿校服，并准时到达。如有任何问题，请联系教务处。' },
      { k: 'blank' },
    ],
    phrases: [
      { zh: '现将有关事项通知如下', pinyin: 'Xiàn jiāng yǒuguān shìxiàng tōngzhī rúxià', en: 'The following matters are hereby announced' },
      { zh: '请各位同学……', pinyin: 'Qǐng gèwèi tóngxué…', en: 'All students are asked to…' },
      { zh: '于……举行', pinyin: 'Yú… jǔxíng', en: 'Will be held at/on…' },
      { zh: '如有疑问，请联系……', pinyin: 'Rú yǒu yíwèn, qǐng liánxì…', en: 'If you have questions, please contact…' },
      { zh: '特此通知', pinyin: 'Tè cǐ tōngzhī', en: 'This notice is hereby issued' },
      { zh: '请准时出席', pinyin: 'Qǐng zhǔnshí chūxí', en: 'Please attend punctually' },
      { zh: '请于……前……', pinyin: 'Qǐng yú… qián…', en: 'Please do … before…' },
      { zh: '敬请注意', pinyin: 'Jìng qǐng zhùyì', en: 'Please be advised' },
    ],
    checklist: [
      { zh: '发布单位', en: 'Issuing body right-aligned' },
      { zh: '日期', en: 'Date right-aligned below issuing body (YYYY年MM月DD日)' },
      { zh: '"通知"标题', en: '"通知" centered as heading' },
      { zh: '受众称呼', en: 'Who the notice is for — left-aligned (全体同学：)' },
      { zh: '内容', en: 'Clear details: what, when, where' },
      { zh: '正文缩进', en: 'Body paragraphs indented 2 characters' },
      { zh: '要求', en: 'What readers must do (请各位……)' },
      { zh: '联系方式', en: 'Contact info provided' },

    ],
  },

  // ─── 6. 博客 (UNCHANGED — not in MD file) ───────────────────────────────────
  {
    id: 'blog', char: '博', zhName: '博客', pinyin: 'bókè', enName: 'Blog Post', color: '#D4AC0D',
    tagline: 'Online personal post for a wide audience',
    formatRules: [
      'Title centered at top',
      'Web address centered below title (e.g. www.myblog.com/用户名)',
      'Publication date centered below web address: 发布于：YYYY年MM月DD日',
      'Open by greeting readers directly (大家好！)',
      'First line of each body paragraph indented 2 Chinese characters (2em)',
      'One blank line between paragraphs',
      'End with an invitation for readers to comment or interact',
      'Engagement stats (Likes, Comments, Shares, Views) shown evenly across the bottom',
    ],
    layout: [
      { k: 'center', t: '我的第一次露营经历', note: 'Title — centered' },
      { k: 'center', t: 'www.myblog.com/大卫', note: 'Blog URL — centered below title' },
      { k: 'center', t: '发布于：2026年4月19日', note: 'Publication date — centered' },
      { k: 'blank' },
      { k: 'indent', t: '大家好！今天我想跟大家分享我上周末第一次露营的经历！', note: 'Open by greeting readers' },
      { k: 'blank' },
      { k: 'indent', t: '说实话，我一开始有点担心，因为我从来没有在外面睡过觉。但是我的朋友们一直鼓励我，所以我决定试一试。我们去了学校附近的一个公园，搭好帐篷之后，我们一起烤了棉花糖，真的太好吃了！' },
      { k: 'blank' },
      { k: 'indent', t: '晚上我们看了很多星星，聊了很多有趣的话题。虽然晚上有一点冷，但是我觉得非常开心和放松。' },
      { k: 'blank' },
      { k: 'indent', t: '这次露营让我明白了，有时候我们要勇敢地尝试新的事情！你们有没有类似的经历？欢迎在下面留言！', note: 'Invite reader interaction at end' },
      { k: 'stats', likes: 128, comments: 14, shares: 7, views: 892 },
    ],
    phrases: [
      { zh: '大家好！', pinyin: 'Dàjiā hǎo!', en: 'Hello everyone!' },
      { zh: '今天我想跟大家分享……', pinyin: 'Jīntiān wǒ xiǎng gēn dàjiā fēnxiǎng…', en: 'Today I want to share with everyone…' },
      { zh: '说实话……', pinyin: 'Shuō shíhuà…', en: 'Honestly speaking…' },
      { zh: '我觉得……', pinyin: 'Wǒ juéde…', en: 'I think / I feel…' },
      { zh: '你们觉得呢？', pinyin: 'Nǐmen juéde ne?', en: 'What do you all think?' },
      { zh: '欢迎留言！', pinyin: 'Huānyíng liúyán!', en: 'Feel free to leave a comment!' },
      { zh: '下次再见！', pinyin: 'Xià cì zàijiàn!', en: 'See you next time!' },
      { zh: '我决定试一试', pinyin: 'Wǒ juédìng shì yi shì', en: 'I decided to give it a try' },
    ],
    checklist: [
      { zh: '标题', en: 'Engaging title — centered' },
      { zh: '网址', en: 'Blog URL centered below title (www.myblog.com/用户名)' },
      { zh: '发布日期', en: 'Publication date centered (发布于：YYYY年MM月DD日)' },
      { zh: '问候读者', en: 'Readers addressed directly at start (大家好！)' },
      { zh: '话题引入', en: 'Topic introduced naturally in opening' },
      { zh: '正文缩进', en: 'Body paragraphs indented 2 characters' },
      { zh: '个人观点', en: 'Personal opinions clearly expressed' },
      { zh: '互动结尾', en: 'Readers invited to respond at the end' },
      { zh: '互动数据', en: 'Engagement stats shown at bottom (Likes, Comments, Shares, Views)' },
    ],
  },

  // ─── 7. 文章 ─────────────────────────────────────────────────────────────────
  // MD spec (文章 = Essay): Title (CA); Body (I2). No sign-off.
  {
    id: 'article', char: '文', zhName: '文章', pinyin: 'wénzhāng', enName: 'Article', color: '#8B1A1A',
    tagline: 'Informative piece for a publication or school paper',
    formatRules: [
      'Headline centered (larger font)',
      'Byline centered below headline: 作者：XX ｜ YYYY年MM月DD日',
      'First line of each body paragraph indented 2 Chinese characters (2em)',
      'One blank line between paragraphs',
      'Quotes formatted as: XX表示："……" or XX说："……"',
      'Conclusion paragraph summarises key points — no signature or closing',
    ],
    layout: [
      { k: 'center', t: '学校举办中国文化节，学生热情参与', note: 'Headline — centered' },
      { k: 'blank' },
      { k: 'center', t: '作者：小明 ｜ 2026年4月15日', note: 'Byline — centered under headline' },
      { k: 'blank' },
      { k: 'indent', t: '上周五，本校在操场举办了一年一度的中国文化节。来自各年级的五百多名学生参加了这次活动，受到了师生的热烈欢迎。', note: 'Lead paragraph — who/what/when/where' },
      { k: 'blank' },
      { k: 'indent', t: '本次活动设有多个展台，包括书法、茶艺、传统服装体验以及中国食品品尝。许多学生表示，这是他们第一次体验传统中国文化，感到非常有趣。' },
      { k: 'blank' },
      { k: 'indent', t: '参与活动的王同学表示："我学会了怎么用毛笔写字，虽然很难，但是非常好玩。"', note: 'Quote — XX表示："……"' },
      { k: 'blank' },
      { k: 'indent', t: '据组织老师介绍，举办此次活动的目的是帮助学生更好地了解中华文化。总的来说，本次文化节取得了圆满成功，学校计划明年继续举办。', note: 'Conclusion — no closing or signature' },
    ],
    phrases: [
      { zh: '据报道……', pinyin: 'Jù bàodào…', en: 'It is reported that…' },
      { zh: '近年来……', pinyin: 'Jìn nián lái…', en: 'In recent years…' },
      { zh: '[人物]表示……', pinyin: '[rénwù] biǎoshì…', en: '[Person] stated that…' },
      { zh: '总的来说……', pinyin: 'Zǒng de lái shuō…', en: 'Overall / In summary…' },
      { zh: '此次活动……', pinyin: 'Cǐ cì huódòng…', en: 'This event…' },
      { zh: '引起了广泛关注', pinyin: 'Yǐnqǐle guǎngfàn guānzhù', en: 'attracted widespread attention' },
      { zh: '受到……欢迎', pinyin: 'Shòudào… huānyíng', en: 'was welcomed by…' },
      { zh: '活动取得圆满成功', pinyin: 'Huódòng qǔdé yuánmǎn chénggōng', en: 'The event was a great success' },
    ],
    checklist: [
      { zh: '标题', en: 'Clear headline — centered' },
      { zh: '作者/日期', en: 'Byline centered: 作者：XX ｜ date' },
      { zh: '导语', en: 'Lead paragraph answers who/what/when/where' },
      { zh: '正文缩进', en: 'Body paragraphs indented 2 characters' },
      { zh: '客观语气', en: 'Objective tone maintained (minimal 我)' },
      { zh: '引用', en: 'Quotes included (XX表示："……")' },
      { zh: '结论', en: 'Conclusion summarises key points — no signature' },
    ],
  },

  // ─── 8. 海报 ─────────────────────────────────────────────────────────────────
  // MD spec: Header topic title (CA) + slogan; Body bullet points with ★;
  //          Footer contact/hotline at absolute bottom (LA)
  {
    id: 'poster', char: '报', zhName: '海报', pinyin: 'hǎibào', enName: 'Poster', color: '#2E7D6B',
    tagline: 'Visual, punchy promotional material',
    formatRules: [
      'Main title centered (largest font, most prominent)',
      'Subtitle or slogan centered below main title',
      'Time, location, cost listed as left-aligned label fields',
      'Event highlights in a bullet list marked with ★ (left-aligned)',
      'Call to action centered (large font, eye-catching)',
      'Contact / hotline details left-aligned at the absolute bottom',
    ],
    layout: [
      { k: 'center', t: '🎉 汉语文化节 🎉', note: 'Main title — centered, large and bold' },
      { k: 'center', t: '感受中华文化之美', note: 'Slogan — centered below title' },
      { k: 'blank' },
      { k: 'field',  label: '时间：', t: '2026年4月25日（星期五）上午9:00–下午3:00', note: 'Details — left-aligned fields' },
      { k: 'field',  label: '地点：', t: '学校礼堂' },
      { k: 'field',  label: '费用：', t: '免费入场' },
      { k: 'blank' },
      { k: 'left',   t: '活动亮点：', note: 'Section heading — left-aligned' },
      { k: 'bullet', t: '传统书法体验' },
      { k: 'bullet', t: '精彩舞龙表演' },
      { k: 'bullet', t: '中国美食品尝' },
      { k: 'bullet', t: '传统服装拍照' },
      { k: 'blank' },
      { k: 'center', t: '名额有限，快快报名！', note: 'Call to action — centered' },
      { k: 'blank' },
      { k: 'left',   t: '报名请联系：王老师', note: 'Contact / hotline — left-aligned at bottom' },
      { k: 'left',   t: '邮件：wang@school.edu' },
    ],
    phrases: [
      { zh: '快来参加！', pinyin: 'Kuài lái cānjiā!', en: 'Come and join us!' },
      { zh: '名额有限', pinyin: 'Míngé yǒuxiàn', en: 'Limited spaces available' },
      { zh: '免费入场', pinyin: 'Miǎnfèi rùchǎng', en: 'Free admission' },
      { zh: '立即报名！', pinyin: 'Lìjí bàomíng!', en: 'Sign up now!' },
      { zh: '不要错过！', pinyin: 'Bùyào cuòguò!', en: "Don't miss it!" },
      { zh: '欢迎所有人参加', pinyin: 'Huānyíng suǒyǒurén cānjiā', en: 'Everyone is welcome' },
      { zh: '活动将于……举行', pinyin: 'Huódòng jiāng yú… jǔxíng', en: 'The event will be held at…' },
      { zh: '精彩不容错过', pinyin: 'Jīngcǎi bù róng cuòguò', en: 'Not to be missed' },
    ],
    checklist: [
      { zh: '大标题', en: 'Bold, large headline centered' },
      { zh: '口号', en: 'Slogan / tagline centered below title' },
      { zh: '时间', en: 'Date and time clearly stated (left-aligned field)' },
      { zh: '地点', en: 'Location included (left-aligned field)' },
      { zh: '费用', en: 'Cost / admission price mentioned (left-aligned field)' },
      { zh: '★亮点列表', en: 'Key highlights in ★ bullet list' },
      { zh: '号召行动', en: 'Call to action centered (名额有限，快快报名！)' },
      { zh: '联系方式', en: 'Contact / hotline details left-aligned at bottom' },
    ],
  },

  // ─── 9. 演讲稿 ──────────────────────────────────────────────────────────────
  // MD spec: Greeting audience (LA + C); "大家好!" (NL, I2); Body (I2);
  //          "谢谢大家!" (NL, CA or RA)
  {
    id: 'speech', char: '演', zhName: '演讲稿', pinyin: 'yǎnjiǎng gǎo', enName: 'Speech', color: '#B5490A',
    tagline: 'Formal spoken address prepared in written form',
    formatRules: [
      'Opening salutation left-aligned at margin with colon: 尊敬的老师们，亲爱的同学们：',
      '"大家好！" indented 2 characters on the next line',
      'First line of each body paragraph indented 2 Chinese characters (2em)',
      'One blank line between paragraphs',
      'Transition words begin each paragraph (首先 / 其次 / 最后)',
      '"谢谢大家！" on a new line, indented 2 characters (left-aligned with indent)',
    ],
    layout: [
      { k: 'left',   t: '尊敬的老师们/亲爱的同学们：', note: 'Opening salutation — left-aligned, ends with colon' },
      { k: 'blank' },
      { k: 'indent', t: '大家好！我叫王明，今天我演讲的题目是"中国传统节日的重要性"。中国有很多重要的传统节日，比如春节、中秋节和端午节，这些节日对我们的文化和生活有非常重要的意义。', note: '"大家好！" begins this indented paragraph' },
      { k: 'blank' },
      { k: 'indent', t: '首先，传统节日让家人能够团聚在一起。以春节为例，无论人们在哪里工作，大多数人都会回家和家人一起吃团圆饭。这种习俗让家庭关系更加紧密。', note: '首先… (first point)' },
      { k: 'blank' },
      { k: 'indent', t: '其次，传统节日帮助我们保护和传承中华文化。每个节日都有自己独特的习俗和故事，通过庆祝这些节日，我们可以把中国的历史和文化传给下一代。', note: '其次… (second point)' },
      { k: 'blank' },
      { k: 'indent', t: '总的来说，中国传统节日是我们文化的重要组成部分。我希望大家都能了解和珍视这些节日。', note: 'Conclusion paragraph' },
      { k: 'blank' },
      { k: 'indent', t: '谢谢大家！', note: 'Closing — left-aligned with 2-char indent' },
    ],
    phrases: [
      { zh: '大家好，我叫……', pinyin: 'Dàjiā hǎo, wǒ jiào…', en: 'Hello everyone, my name is…' },
      { zh: '我演讲的题目是……', pinyin: 'Wǒ yǎnjiǎng de títù shì…', en: 'The topic of my speech is…' },
      { zh: '首先……其次……最后……', pinyin: 'Shǒuxiān… qícì… zuìhòu…', en: 'First… secondly… finally…' },
      { zh: '以……为例……', pinyin: 'Yǐ… wéi lì…', en: 'Taking… as an example…' },
      { zh: '总的来说……', pinyin: 'Zǒng de lái shuō…', en: 'In summary…' },
      { zh: '我认为……', pinyin: 'Wǒ rènwéi…', en: 'I believe that…' },
      { zh: '谢谢大家！', pinyin: 'Xièxiè dàjiā!', en: 'Thank you everyone!' },
      { zh: '希望大家……', pinyin: 'Xīwàng dàjiā…', en: 'I hope everyone…' },
    ],
    checklist: [
      { zh: '开场称呼', en: 'Opening salutation left-aligned, ends with colon (尊敬的……：)' },
      { zh: '大家好缩进', en: '"大家好！" indented 2 chars at start of first paragraph' },
      { zh: '题目介绍', en: 'Topic introduced in opening paragraph' },
      { zh: '正文缩进', en: 'Each body paragraph indented 2 characters' },
      { zh: '过渡词', en: 'Transition words used (首先 / 其次 / 最后)' },
      { zh: '段落空行', en: 'Blank line between paragraphs' },
      { zh: '个人观点', en: 'Opinion clearly stated (我认为 / 我觉得)' },
      { zh: '结论段', en: 'Summary paragraph before closing' },
      { zh: '谢谢大家缩进', en: '"谢谢大家！" indented (left-aligned with 2-char indent) at the end' },
    ],
  },

  // ─── 10. 访谈录 (UNCHANGED — not in MD file) ────────────────────────────────
  {
    id: 'interview', char: '访', zhName: '访谈录', pinyin: 'fǎngtán lù', enName: 'Interview', color: '#2E7D8B',
    tagline: 'Written record of a question-and-answer interview',
    formatRules: [
      'Title centered at top',
      'Interviewee introduction left-aligned',
      'Divider line separates introduction from Q&A',
      'Interviewer label left-aligned at margin: 记者：',
      'Interviewee label left-aligned at margin: XX：',
      'One blank line between question and answer',
      'One blank line between each Q&A exchange',
    ],
    layout: [
      { k: 'center', t: '专访：我的汉语学习之旅', note: 'Title — centered' },
      { k: 'blank' },
      { k: 'left',   t: '受访者：李华，本校汉语学习优秀学生', note: 'Interviewee intro — left-aligned' },
      { k: 'divider', note: 'Divider between intro and Q&A' },
      { k: 'qa', role: '记者', t: '请问你学习汉语多久了？为什么选择学习汉语？', isQ: true, note: 'Interviewer — left-aligned role label' },
      { k: 'blank' },
      { k: 'qa', role: '李华', t: '我学习汉语已经两年了。我选择学习汉语是因为我对中国文化非常感兴趣，而且我认为汉语在未来会非常有用。', isQ: false, note: 'Interviewee — left-aligned role label' },
      { k: 'blank' },
      { k: 'qa', role: '记者', t: '学习汉语最大的挑战是什么？', isQ: true },
      { k: 'blank' },
      { k: 'qa', role: '李华', t: '我觉得最大的挑战是汉字。汉字很多，而且每个字的写法都不一样。但是通过每天练习，我慢慢地进步了。', isQ: false },
      { k: 'blank' },
      { k: 'qa', role: '记者', t: '你有什么建议给刚开始学习汉语的同学吗？', isQ: true },
      { k: 'blank' },
      { k: 'qa', role: '李华', t: '我的建议是每天坚持练习，不要怕犯错。多看中文电影和听中文歌曲也很有帮助。最重要的是，要对汉语保持热情！', isQ: false },
    ],
    phrases: [
      { zh: '请问……', pinyin: 'Qǐngwèn…', en: 'May I ask…' },
      { zh: '您能介绍一下……吗？', pinyin: 'Nín néng jièshào yīxià… ma?', en: 'Could you introduce…?' },
      { zh: '我认为……', pinyin: 'Wǒ rènwéi…', en: 'I believe that…' },
      { zh: '从我的经验来看……', pinyin: 'Cóng wǒ de jīngyàn lái kàn…', en: 'From my experience…' },
      { zh: '对我来说……', pinyin: 'Duì wǒ lái shuō…', en: 'For me…' },
      { zh: '非常感谢您接受我们的采访', pinyin: 'Fēicháng gǎnxiè nín jiēshòu wǒmen de cǎifǎng', en: 'Thank you very much for the interview' },
      { zh: '最后，请问……', pinyin: 'Zuìhòu, qǐngwèn…', en: 'Finally, may I ask…' },
      { zh: '我的建议是……', pinyin: 'Wǒ de jiànyì shì…', en: 'My suggestion is…' },
    ],
    checklist: [
      { zh: '标题', en: 'Title centered at top' },
      { zh: '受访者介绍', en: 'Interviewee briefly introduced — left-aligned' },
      { zh: '分隔线', en: 'Divider between intro and Q&A' },
      { zh: '记者标签', en: 'Interviewer label left-aligned (记者：)' },
      { zh: '受访者标签', en: 'Interviewee label left-aligned (name：)' },
      { zh: '问答空行', en: 'Blank line between each Q&A exchange' },
      { zh: '3组以上', en: 'At least 3 question-and-answer pairs' },
      { zh: '语气', en: 'Formal but conversational tone throughout' },
    ],
  },

  // ─── 11. 广告 ────────────────────────────────────────────────────────────────
  {
    id: 'ad', char: '广', zhName: '广告', pinyin: 'guǎnggào', enName: 'Advertisement', color: '#C0392B',
    tagline: 'Promotional text designed to attract and persuade',
    formatRules: [
      'Main title centered (bold, eye-catching)',
      'Body text centered or left-aligned',
      'Key selling points can be listed as bullet points (★)',
      '联系人 (contact person) right-aligned',
      'Contact details (phone / address / 点…) right-aligned below 联系人',
    ],
    layout: [
      { k: 'center', t: '学中文，走世界！', note: 'Main slogan — centered, bold and punchy' },
      { k: 'center', t: '——汉语暑期强化班招生启事', note: 'Subtitle — centered' },
      { k: 'blank' },
      { k: 'left',   t: '活动亮点：', note: 'Section heading — left-aligned' },
      { k: 'bullet', t: '小班教学，每班不超过10人' },
      { k: 'bullet', t: '由经验丰富的汉语老师授课' },
      { k: 'bullet', t: '涵盖听说读写全面训练' },
      { k: 'bullet', t: '结业后颁发证书' },
      { k: 'blank' },
      { k: 'center', t: '名额有限，欲报从速！', note: 'Call to action — centered' },
      { k: 'blank' },
      { k: 'right',  t: '联系人：王老师', note: '联系人 — right-aligned' },
      { k: 'right',  t: '电话：012-3456789', note: 'Contact details — right-aligned' },
      { k: 'right',  t: '地点：学校语言中心 101室', note: 'Location — right-aligned' },
    ],
    phrases: [
      { zh: '欢迎报名！', pinyin: 'Huānyíng bàomíng!', en: 'Sign-ups welcome!' },
      { zh: '名额有限，欲报从速', pinyin: 'Míngé yǒuxiàn, yù bào cóng sù', en: 'Limited spots — register soon' },
      { zh: '详情请联系……', pinyin: 'Xiángqíng qǐng liánxì…', en: 'For details, please contact…' },
      { zh: '免费入场', pinyin: 'Miǎnfèi rùchǎng', en: 'Free admission' },
      { zh: '特价优惠', pinyin: 'Tèjià yōuhuì', en: 'Special discounted price' },
      { zh: '不要错过！', pinyin: 'Bùyào cuòguò!', en: "Don't miss it!" },
      { zh: '立即报名！', pinyin: 'Lìjí bàomíng!', en: 'Register now!' },
      { zh: '全面提升你的汉语水平', pinyin: 'Quánmiàn tíshēng nǐ de Hànyǔ shuǐpíng', en: 'Comprehensively improve your Chinese level' },
    ],
    checklist: [
      { zh: '大标题', en: 'Bold, eye-catching title — centered' },
      { zh: '卖点', en: 'Key selling points listed (bullet points or centered text)' },
      { zh: '号召行动', en: 'Call to action centered (名额有限，欲报从速！)' },
      { zh: '联系人', en: '联系人 right-aligned' },
      { zh: '联系方式', en: 'Contact details (phone / address) right-aligned' },
      { zh: '语气吸引人', en: 'Persuasive, enthusiastic tone throughout' },
    ],
  },

  // ─── 12. 邀请 ────────────────────────────────────────────────────────────────
  {
    id: 'invitation', char: '邀', zhName: '邀请', pinyin: 'yāoqǐng', enName: 'Invitation', color: '#7B6EA8',
    tagline: 'Formal or informal written invitation to an event',
    formatRules: [
      'Recipient left-aligned at margin with colon: 亲爱的XX：',
      'First line of each body paragraph indented 2 Chinese characters (2em)',
      'State the event, date, time and location clearly in the body',
      'One blank line between paragraphs',
      'Closing phrase such as 敬请光临 or 期待您的到来 — left-aligned or indented',
      'Sender name right-aligned',
      'Date right-aligned on the line below the name',
    ],
    layout: [
      { k: 'left',   t: '亲爱的李华：', note: 'Recipient — left-aligned, ends with colon (：)' },
      { k: 'blank' },
      { k: 'indent', t: '您好！我很高兴地邀请您参加我们学校举办的汉语文化节。', note: 'Opening — state the invitation clearly' },
      { k: 'blank' },
      { k: 'indent', t: '活动将于2026年5月10日（星期六）上午十点在学校礼堂举行。本次活动将包括书法表演、中国传统音乐以及美食品尝等精彩环节，相信您一定会喜欢！', note: 'Body — event details: what, when, where' },
      { k: 'blank' },
      { k: 'indent', t: '如果您能出席，请在5月5日前回复我。期待与您共度愉快的一天！' },
      { k: 'blank' },
      { k: 'indent', t: '敬请光临！', note: 'Closing phrase — indented' },
      { k: 'blank' },
      { k: 'right',  t: '王明', note: 'Sender name — right-aligned' },
      { k: 'right',  t: '2026年4月28日', note: 'Date — right-aligned below name' },
    ],
    phrases: [
      { zh: '我很高兴地邀请您……', pinyin: 'Wǒ hěn gāoxìng de yāoqǐng nín…', en: 'I am delighted to invite you to…' },
      { zh: '活动将于……举行', pinyin: 'Huódòng jiāng yú… jǔxíng', en: 'The event will be held at/on…' },
      { zh: '敬请光临', pinyin: 'Jìng qǐng guānglín', en: 'Your presence is respectfully requested' },
      { zh: '期待您的到来', pinyin: 'Qīdài nín de dàolái', en: 'Looking forward to your arrival' },
      { zh: '请在……前回复', pinyin: 'Qǐng zài… qián huífù', en: 'Please reply by…' },
      { zh: '如蒙光临，不胜荣幸', pinyin: 'Rú méng guānglín, bù shèng róngxìng', en: 'We would be honoured by your presence' },
      { zh: '相信您一定会喜欢', pinyin: 'Xiāngxìn nín yīdìng huì xǐhuān', en: 'We are sure you will enjoy it' },
      { zh: '希望您能出席', pinyin: 'Xīwàng nín néng chūxí', en: 'We hope you can attend' },
    ],
    checklist: [
      { zh: '称呼', en: 'Recipient named at start — left-aligned, ends with colon' },
      { zh: '邀请说明', en: 'Invitation clearly stated in opening paragraph' },
      { zh: '活动名称', en: 'Name of the event mentioned' },
      { zh: '时间', en: 'Date and time clearly stated' },
      { zh: '地点', en: 'Location included' },
      { zh: '回复要求', en: 'Reader asked to reply by a certain date' },
      { zh: '结束语', en: 'Closing phrase (敬请光临 / 期待您的到来)' },
      { zh: '署名', en: 'Sender name right-aligned' },
      { zh: '日期', en: 'Date right-aligned below name' },
    ],
  },

  // ─── 13. 申请信 (UNCHANGED — not in MD file) ────────────────────────────────
  {
    id: 'application', char: '申', zhName: '申请信', pinyin: 'shēnqǐng xìn', enName: 'Application Letter', color: '#8B4513',
    tagline: 'Formal letter applying for a position, programme or opportunity',
    formatRules: [
      'Formal salutation left-aligned at margin with colon: 尊敬的……：',
      'First line of each body paragraph indented 2 Chinese characters (2em)',
      'First paragraph: clearly state the purpose of the application',
      'Second paragraph: describe your qualifications or relevant experience',
      'Third paragraph: express hope and thank the reader',
      'One blank line between paragraphs',
      'Formal closing right-aligned: 此致敬礼，',
      'Name right-aligned below closing phrase',
      'Date right-aligned at bottom: YYYY年MM月DD日 format',
    ],
    layout: [
      { k: 'left',   t: '尊敬的招生委员会：', note: 'Formal salutation — left-aligned, ends with colon' },
      { k: 'blank' },
      { k: 'indent', t: '我叫王明，是本校十年级的学生。我写信是为了申请贵校暑期汉语强化课程的参加名额，希望能通过这个机会提高我的汉语水平。', note: 'Para 1 — state purpose' },
      { k: 'blank' },
      { k: 'indent', t: '我学习汉语已经两年，在课堂中取得了良好的成绩。我对中国文化有浓厚的兴趣，曾多次参加学校的文化活动。我认为贵校的课程将帮助我更系统地学习汉语，为将来的深造打好基础。', note: 'Para 2 — qualifications' },
      { k: 'blank' },
      { k: 'indent', t: '如蒙录取，我将认真学习，珍惜这次机会。我期待能够收到您的回复，非常感谢您考虑我的申请。', note: 'Para 3 — hope & thanks' },
      { k: 'blank' },
      { k: 'right',  t: '此致敬礼，', note: 'Formal closing — right-aligned' },
      { k: 'right',  t: '王明', note: 'Name — right-aligned' },
      { k: 'right',  t: '2026年04月19日', note: 'Date — bottom right (YYYY年MM月DD日)' },
    ],
    phrases: [
      { zh: '我写信是为了申请……', pinyin: 'Wǒ xiě xìn shì wèile shēnqǐng…', en: 'I am writing to apply for…' },
      { zh: '希望能通过……提高……', pinyin: 'Xīwàng néng tōngguò… tígāo…', en: 'I hope to improve… through…' },
      { zh: '我认为……将帮助我……', pinyin: 'Wǒ rènwéi… jiāng bāngzhù wǒ…', en: 'I believe… will help me…' },
      { zh: '如蒙录取……', pinyin: 'Rú méng lùqǔ…', en: 'If accepted…' },
      { zh: '非常感谢您考虑我的申请', pinyin: 'Fēicháng gǎnxiè nín kǎolǜ wǒ de shēnqǐng', en: 'Thank you very much for considering my application' },
      { zh: '期待收到您的回复', pinyin: 'Qīdài shōudào nín de huífù', en: 'Looking forward to your reply' },
      { zh: '此致敬礼', pinyin: 'Cǐ zhì jìng lǐ', en: 'Yours respectfully' },
      { zh: '我对……有浓厚的兴趣', pinyin: 'Wǒ duì… yǒu nónghòu de xìngqù', en: 'I have a strong interest in…' },
    ],
    checklist: [
      { zh: '正式称呼', en: 'Formal salutation left-aligned, ends with colon (：)' },
      { zh: '第一段目的', en: 'Opening paragraph states purpose of application' },
      { zh: '第二段条件', en: 'Middle paragraph covers qualifications / experience' },
      { zh: '第三段期望', en: 'Final paragraph expresses hope and gratitude' },
      { zh: '正文缩进', en: 'Each paragraph indented 2 characters' },
      { zh: '段落空行', en: 'Blank line between paragraphs' },
      { zh: '结束语', en: 'Formal closing right-aligned (此致敬礼，)' },
      { zh: '署名', en: 'Name right-aligned below closing' },
      { zh: '日期（信尾）', en: 'Date bottom right: YYYY年MM月DD日' },
    ],
  },
];
